name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      aws-statefile-s3-bucket:
        required: true
        type: string
      aws-lock-dynamodb-table:
        required: true
        type: string
    secrets:
      aws-assume-role-arn:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}

      - name: "Initialize Terraform"
        run: |
          cd infra && terraform init \
            -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=${{ inputs.aws_region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamodb-table }}"

      - name: "Validate Terraform configuration"
        run: terraform validate

      - name: "Plan Terraform"
        id: terraform-plan
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="envs/${{ inputs.environment }}/terraform.tfvars" -out=${{ inputs.environment }}.plan

      - name: "Apply Terraform"
        id: terraform-apply
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply ${{ inputs.environment }}.plan
